docker run -it \
  -e POSTGRES_USER="root"\
  -e POSTGRES_PASSWORD="root"\
  -e POSTGRES_DB="ny_taxi"\
  -v $(pwd)/ny_taxi_postgres_data:/var/lib/postgressql/data\
  -p 5432:5432\
postgres:13


docker run -it \
  -e PGADMIN_DEAFAULT_EMAIL="yuqingyang563@gmail.com"\
  -e PGADMIN_DEAFAULT_PASSWORD="root"\
  -p 8080:80\
  dpage/pgadmin4



## network

docker network create pg-network

docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v $(pwd)/ny_taxi_postgres_data:/var/lib/postgressql/data \
  -p 5432:5432 \ 
  --network=pg-network \
  --name pg-database \
postgres:13



docker run -it \
  -e PGADMIN_DEAFAULT_EMAIL="yuqingyang563@gmail.com"\
  -e PGADMIN_DEAFAULT_PASSWORD="root"\
  -p 8080:80\
  --network=pg-network \
  --name pgadmin \
  dpage/pgadmin4
